# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170420_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='name',
            field=models.CharField(default='Rem', max_length=100, unique=True),
        ),
    ]
