# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mailbox_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailHtml',
        ),
    ]
