# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_mailhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='connected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
